### ISSUE TITLE
Input from a Shields maintainer

### ISSUE THREAD

**Issue by paulmelnikow** [mightyiam/shields-badge-data#22]
Hi! I'm responding to your request for input at badges/shields#1226.

It's always really fun to see people building things with Shields. :grin:

This is a really neat project and looks great.

I read through it and I have a few suggestions. One is long but I think compelling, so I'll open a separate issue to discuss it and link below. Most of my ideas are short so I'll enumerate them right here, though if you'd prefer to discuss any of them in separate issues, by all means we could continue the conversation that way.

I love that this could run in a browser!

It's cool that you're using the JSON-ish services list. It felt like such progress converting that from HTML into this more usable format, and it's neat to see that being used, even as a todo list.

You'd asked about generating links for services. The only code we have for that is in [lib/suggest.js](https://github.com/badges/shields/blob/master/lib/suggest.js) which is used for the badge suggestions. I'd love to have that more closely coupled with each service in the future though! And happy to try to collect that information as best I can going forward.

I'd suggest providing an option to get Markdown output. That could be helpful for skeleton generation, for example, or simply generating blocks that are ready to paste into a readme. It's common practice to wrap the Shields image in a link because links embedded in SVGs do not work in web pages when using `<img src=""`. You need to use `<object data="">` instead, and that's not a possibility in a Github readme. (Well… I'm about 90% sure that is all true. Shields is a surprisingly complicated project and this is an area where I am still getting up to speed.)

In terms of code organization, would it be possible to put all the code for a service in one place, like a ServiceDefinition type? This kind of grouping – by coupling instead of function – can make it easier for contributors to wrap their head around what's needed to add a service, more convenient since it it doesn't require editing so many files, and less prone to merge conflicts. Shields itself is moving in this direction, starting with badges/shields#963.

Have you given thought to validation of string parameters, such as a regex? Certainly this is something that could be added later, though I'm not sure if it might affect your design choices now.

The list of named logos supported by Shields is changing pretty quickly. There's been some discussion of a shields data format in badges/shields#776 and it's something I'd like to support. I'm keen to get that started. Even if you're only using it for the logos, I wouldn't mind the kickstart.

I'm 99% sure it's possible to pass a single link to Shields, in which case the same link is used for both parts. You may already be allowing that; not sure; I didn't dig in too deep. I'm still learning to read TypeScript. 😁 

Some people self-host shields. It might be nice to provide a command-line argument to let them override the base URL.

One last thought: would `shields-badge-url` be a tighter name?

**Comment by paulmelnikow** [comment]
See also **Multiple services from the same provider (#23)**

**Comment by mightyiam** [comment]
> This is a really neat project and looks great.

Thanks, a lot!

> I love that this could run in a browser!

While I didn't test it, in theory, the `package.json` `browser` field should make that possible. Definitely my intention.


> I'd suggest providing an option to get Markdown output.

I would see that as a separate package.

> In terms of code organization, would it be possible to put all the code for a service in one place, like a ServiceDefinition type?

#24

> Have you given thought to validation of string parameters, such as a regex? Certainly this is something that could be added later, though I'm not sure if it might affect your design choices now.

I believe some would call this "defensive programming", which I tend to not see the value of. This might compounded by my wide use of TypeScript, in general. In this case, TypeScript won't help, because a string is a string. I'm willing to see a PR, I guess.

RE: badges data format:

https://github.com/badges/shields/issues/776#issuecomment-341138694

> I'm 99% sure it's possible to pass a single link to Shields, in which case the same link is used for both parts. You may already be allowing that; not sure; I didn't dig in too deep. I'm still learning to read TypeScript.

Meh.

> Some people self-host shields. It might be nice to provide a command-line argument to let them override the base URL.

But there is no command line interface. That would be an API option, as I see it: #25.

> One last thought: would `shields-badge-url` be a tighter name?

Yup. Will do.

**Comment by paulmelnikow** [comment]
> I believe some would call this "defensive programming", which I tend to not see the value of.

I'm not sure I'd call it that. It's more about enabling a good user experience with helpful error messages, rather than outputting a badge URL that doesn't work, and then the user having to dig in to find out why. (Shields down? Upstream server broken? Badge code not working? Problem in this library? Typo? Something not escaped properly?)

**Comment by mightyiam** [comment]
Alright. I agree. See #26. I think we're done splitting this conversation apart. Thank you and good luck.
