### ISSUE TITLE
CC0 license

### ISSUE THREAD

**Issue by paulmelnikow** [mightyiam/shields-badge-data#28]
Following on https://github.com/badges/shields/issues/1226#issuecomment-340762809

Could I remind you about this? Thanks!

**Comment by mightyiam** [comment]
Of course, @paulmelnikow. Thank you.

**Comment by mightyiam** [comment]
I'm a bit concerned:
https://opensource.org/faq#cc-zero

**Comment by paulmelnikow** [comment]
The OSI debate centered around patents, which is probably not relevant unless you or other contributors have patents. The [FSF recommends it for works in the public domain](https://www.gnu.org/licenses/license-list.en.html#CC0). Both are mentioned in badges/shields#104 when the license was determined. For what it's worth, I imagine the public domain dedication streamlined the adoption of the shields badge specification, which the project has convinced many, many commercial entities to use.

What about dual CC0 + ISC, if you're still concerned?

**Comment by mightyiam** [comment]
I have asked in the Open Source Initiative's mailing list:
https://lists.opensource.org/pipermail/license-discuss/2017-November/019984.html

**Comment by mightyiam** [comment]
@paulmelnikow look, there's [a response](https://lists.opensource.org/pipermail/license-discuss/2017-November/019985.html).

I'm not in open source to deal with such things as license and legal questions.

Is there any other way to resolve this?

Are you sure that you cannot use this if it is licensed ISC or MIT, for example? The `package.json` has lots of non CC0 dependencies...
https://github.com/badges/shields/blob/master/package.json

**Comment by mightyiam** [comment]
After the [last response](https://lists.opensource.org/pipermail/license-discuss/2017-November/019991.html) I decided to revert it back. Hey, @paulmelnikow, are you certain that there's an issue here, with this being ISC, at all?

**Comment by paulmelnikow** [comment]
> I'm not in open source to deal with such things as license and legal questions.

Makes two of us! 😉 

I'm interested in growing an ecosystem around Shields, so I'm happy to help develop designs, code, and validation rules here, and help you build an easy-to-use tool. My concern is that I don't want to be restricted from mixing aspects of that work, such as the service definition design, or service definitions themselves, back into Shields later.

To take a step back: perhaps I'm not understanding, but it wouldn't make sense to define the service rules here and then pull them into Shields as a dependency. The canonical source of which badges are available, along with their validation rules, eventually needs to be the Shields repository.

> Is there any other way to resolve this?

I understand if you're set on using ISC.

I could keep any work I do on a service definitions API in the main repo, for avoidance of this restriction.

**Comment by mightyiam** [comment]
> ...eventually needs to be the Shields repository.

"Uder the control of the shields organization", I would say. Yet, for the sake of good modularity, I would say as a separate repo and package, in the "badges" organization. I'll gladly cooperate on that. It seems that this is exactly what I'm writing here. And it makes sense that it be contributed entirely into the badges organization.

In that case, I'd love to be a collaborator. In that sense, I cannot dictate the license. Nevertheless, I will contribute.

Will you accept the transfer of this repository and all rights I can legally transfer into the "badges" organization?

**Comment by paulmelnikow** [comment]
Hey, sorry, I missed this before! Thanks for the heads-up.

Agreed things should be decoupled and modularized when they can. It makes sense to have a separate module / library, decoupled from the main repo, which end users can install to generate badge URLs programmatically.

However, the code that runs a service should live alongside its tests, examples, validation rules, and documentation. It's important that we keep them in sync, and also version them together, since often they will change at the same time, and the frontend will need to use the version of the definitions that matches the deployed code. Two repos would create extra overhead (many changes would need two PRs) and complicate versioning.

It seems like there is a way to keep the badge URL generation code decoupled, as you suggest, while keeping the badge format definitions alongside the code that implements them.

By the way, the first time I saw the principle articulated was by @focusaurus: "Group by Coupling, Not by Function." He was [writing about MVC](https://github.com/focusaurus/express_code_structure), but the principle applies to any code. It's influenced my thinking a lot.

If you're interested in joining the team, why don't we start by working together some more?
